# .streamlit/secrets.toml

SUPABASE_URL = "https://npvwctwurhttdzvbvgcz.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdndjdHd1cmh0dGR6dmJ2Z2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Nzc0ODUsImV4cCI6MjA2NzE1MzQ4NX0.F2ZF_FdwGO4qvEHRB75FSbZ_GBdVesoGJRiu0IpMuXg"
ADMIN_EMAILS = ["mmueller4@rogers.com"]