# .streamlit/secrets.toml

SUPABASE_URL = "https://ggqnlqhncarooowdgfpo.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdncW5scWhuY2Fyb29vd2RnZnBvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MjQzMjQ2MSwiZXhwIjoyMDY4MDA4NDYxfQ.-upxv-odXJDtsK0uCUlP7AEw8BKPE_ST_qaCnEFUODc"
ADMIN_EMAILS = ["b_sarabpreet@yahoo.com"]